### ISSUE TITLE
Roadmap: RC1

### ISSUE THREAD

**Issue by jbreeden** [jbreeden/rubium#2]
- [x] CLI
  - [x] Usage/help message
- [ ] Building
  - [x] #1 Windows build is broken
  - [ ] Provide SDK's for each platform
    - CEF doesn't like robots using their download page.
    - Additionally, building from scratch requires a few manual steps that differ on each platform.
    - The SDK's should have CEF & APR pre-packaged & configured for building with Rubium.
    - Building would then be a matter of downloading the SDK and running a rake task.
- [ ] [mruby-apr RC1](https://github.com/jbreeden/mruby-apr/issues/5)
- [ ] Testing 
  - [x] All test cases in the javascript_interop sample should work. 
  - [ ] Need a better testing output. Too much manual inspection is required at the moment.
- [ ] Samples
  - [ ] Add some short, feature-target examples (bonus points if they're actually useful utilities).
  - [ ] mruby-edit could be a fun way to explore mruby & rubium. Should probably make this stable (and rename...?).
- [ ] Documentation.
  - I cut out the readme when switching from [lamina](http://github.com/jbreeden/lamina) to rubium,
    since most of the information was outdated. Need to create a full wiki with topics for:
  - [ ] Building
  - [ ] Installing
  - [ ] Quick Start (hello world, running by index.html, command line params, dev tools etc)
  - [ ] Ref: JavaScript interop API

**Comment by jbreeden** [comment]
Separating out the important bits into other issues. Putting this all in one list was silly.

**Comment by mibamur** [comment]
very usefull - why it closed?
any news?
last commit 85361e1ff3861f674459c529564f6d63962444f8 :-(

**Comment by jbreeden** [comment]
The bug in that last commit was driving me insane! Around the same time, I got busy with other projects and just haven't gotten back to this yet. That said, I really want to see this project through to a useful end. I just need to find time to pick it back up.

I've also been working on some satellite projects (like mruby-libuv & mruby-rx). Granted, my progress there has been slow as well. (Day job is keeping me pretty busy lately.) But, I wanted to sort out the event loop I'd use if I added a background mruby thread to the browser process that the code on any page could hit.

Building all the libraries that are required to make this thing useful is pretty laborious in general. mruby-apr provides the core ruby libraries from cruby (some of them, anyway), and that alone is a pretty large burden. I was working towards getting rubyspec working on mruby-apr to help me move forward... and I think I just got wore out.

It's nice to have somebody take an interest in the project though. Maybe this weekend I can try to resolve the mruby lifecycle management issues again. In the meantime, I'm always happy to answer questions and try to help you along if you're using the project.

**Comment by mibamur** [comment]
better doc and build tools - is first step to community IMHO )))

**Comment by jbreeden** [comment]
Or maybe, a better community is the first step to better docs and build tools :P

**Comment by mibamur** [comment]
ok
please ping me next week and I will try made something like this https://github.com/hone/mruby-cli/wiki/StarteKit
